---
title: "Open Policing Project Tutorial for Wichita, Kansas"
Author: Kyle Stithem
output:
  html_document:
    code_folding: hide
---

## Setup

First, let's load the necessary libraries and data that will allow us to
begin our investigation!

```{r setup, message=FALSE,  warning=FALSE}
## Libraries to include
library(tidyverse)
library(lubridate)


## Load the data
# Replace the path below with the path to where your data lives
data_path <-"https://datajournalism.tech/wp-content/uploads/2019/10/wichita.csv"
stops <- read_csv(data_path)

# Additional data and fixed values we'll be using
population_2016 <- tibble(
  subject_race = c(
    "asian/pacific islander", "black", "hispanic", "other/unknown","white"
    ),
  num_people = c(19294, 42485, 65090, 16686, 245499)
) %>% 
  mutate(subject_race = as.factor(subject_race))

center_lat <- 37.689789
center_lng <- -97.322720
```

## Data Analysis


```{r}
colnames(stops)
nrow(stops)
str(stops)
summary(stops)
```

How many stops do we have in our dataset? (**Hint**: Try the `nrow()` function.)

```{r}
stops %>% 
  group_by(subject_race) %>% 
  summarize(
    n = n(),
    prop = n / nrow(.)
  )
```
```{r}
race <- stops %>% 
  group_by(subject_race) %>% 
  summarize(
    n = n(),
    prop = n / nrow(.)
  )

race
```



```{r}
population_2016 %>% 
  mutate(prop = num_people / sum(num_people))
```
```{r}
left_join(population_2016, race,
  by="subject_race") %>% mutate(stop_rate=n/num_people)

```




## Data Visualization
## Bar Chart
```{r bar-chart}
#data prep
barprep <- left_join(population_2016, race,
  by="subject_race") %>% mutate(stop_rate=n/num_people)
    
#make the plot

bar <- ggplot(barprep,
       aes(x=reorder(subject_race,stop_rate), y=stop_rate))+
  geom_bar(stat="identity", 
           position="identity", 
           fill="red")+
  geom_hline(yintercept = 0) +
  labs(title="Stopped Drivers by Race",
       subtitle = "African American drivers got stopped more than white American drivers in the city of Witchita, Kansas")+
  coord_flip()

options(scipen=10000)

bar
```
```{r}
#install.packages("httpuv")
#install.packages("leaflet")
library(httpuv)
library(leaflet)
```


## Interactive Map
```{r}
race<- colorFactor(c("azure","gray20","gold1","firebrick1","gray87"),
                   domain=c("white","black","asain/pacific islander","hispanic","other/unknown"),
                   ordered=TRUE)
f <- stops %>% drop_na(lat,lng)
  map<-leaflet(f) %>%
    addProviderTiles(providers$CartoDB) %>% 
    setView(lng = center_lng, lat=center_lat, zoom=10) %>% 
    addCircleMarkers(~lng,
                     ~lat,
                     popup = paste("This is a",f$subject_race,"and",f$subject_sex,"driver."),
                     weight=3,
                     radius=4,
                     color=~race(subject_race),
                     stroke=F,
                     fillOpacity = 1)
  map 
```

